# Generated by Django 4.2.3 on 2023-07-20 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_task_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
