# Generated by Django 4.2.3 on 2023-07-20 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_weektemplate_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weektemplate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
